name: Documentation
on:
  push:
    branches:
      - main
      - next
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - if: github.ref == 'refs/heads/main'
        run: mike deploy --push --update-aliases stable latest
      - if: github.ref == 'refs/heads/main'
        run: mike set-default --push latest
      - if: github.ref == 'refs/heads/next'
        run: mike deploy --push next
